-- Create a new SQL Server Login
CREATE LOGIN RESERVATION 
WITH PASSWORD = 'MANAGER'; -- Use a strong password instead of 'MANAGER'

-- Create a Database User associated with the Login
USE [master]; -- Use the desired database if specific access is needed
CREATE USER RESERVATION 
FOR LOGIN RESERVATION;

-- Grant sysadmin privileges to the user (equivalent to DBA role in Oracle)
EXEC sp_addsrvrolemember @loginame = 'RESERVATION', @rolename = 'sysadmin';
-- Create CUSTOMER table
CREATE TABLE CUSTOMER 
(	
    MAILID NVARCHAR(40) PRIMARY KEY, 
    PWORD NVARCHAR(20) NOT NULL, 
    FNAME NVARCHAR(20) NOT NULL, 
    LNAME NVARCHAR(20), 
    ADDR NVARCHAR(100), 
    PHNO BIGINT NOT NULL
);
-- Create ADMIN table
CREATE TABLE ADMIN
(	
    MAILID NVARCHAR(40) PRIMARY KEY, 
    PWORD NVARCHAR(20) NOT NULL, 
    FNAME NVARCHAR(20) NOT NULL, 
    LNAME NVARCHAR(20), 
    ADDR NVARCHAR(100), 
    PHNO BIGINT NOT NULL
);
CREATE TABLE TRAIN 
(	
    TR_NO INT PRIMARY KEY, 
    TR_NAME NVARCHAR(70) NOT NULL, 
    FROM_STN NVARCHAR(20) NOT NULL, 
    TO_STN NVARCHAR(20) NOT NULL, 
    SEATS SMALLINT NOT NULL, 
    FARE DECIMAL(6,2) NOT NULL 
);
CREATE TABLE HISTORY 
(	
    TRANSID NVARCHAR(36) PRIMARY KEY, 
    MAILID NVARCHAR(40) FOREIGN KEY REFERENCES CUSTOMER(MAILID), 
    TR_NO INT NOT NULL FOREIGN KEY REFERENCES TRAIN(TR_NO),
    DATE DATE NOT NULL,
    FROM_STN NVARCHAR(20) NOT NULL, 
    TO_STN NVARCHAR(20) NOT NULL, 
    SEATS SMALLINT NOT NULL, 
    AMOUNT DECIMAL(8,2) NOT NULL
);

-- Insert data into ADMIN table
INSERT INTO ADMIN VALUES ('admin@demo.com', 'admin', 'System', 'Admin', 'Demo Address 123 colony', 9874561230);

-- Insert data into CUSTOMER table
INSERT INTO CUSTOMER VALUES ('shashi@demo.com', 'shashi', 'Shashi', 'Raj', 'Kolkata, West Bengal', 954745222);

-- Insert data into TRAIN table
INSERT INTO TRAIN (TR_NO, TR_NAME, FROM_STN, TO_STN, SEATS,FARE)VALUES
(10001,'JODHPUR EXP', 'HOWRAH','JODHPUR', 152, 490.50),
(10002, 'YAMUNA EXP', 'GAYA', 'DELHI', 52, 550.50),
(10003, 'NILANCHAL EXP', 'GAYA', 'HOWRAH', 92, 451.00),
(10004, 'JAN SATABDI EXP', 'RANCHI', 'PATNA', 182, 550.00),
(10005, 'GANGE EXP', 'MUMBAI', 'KERALA', 12, 945.00),
(10006, 'GARIB RATH EXP', 'PATNA', 'DELHI', 1, 1450.75);

-- Insert data into HISTORY table
INSERT INTO HISTORY (TRANSID, MAILID, TR_NO, DATE, FROM_STN, TO_STN, SEATS, AMOUNT ) VALUES 
('BBC374-NSDF-4673', 'shashi@demo.com', 10001, '2024-02-02', 'HOWRAH', 'JODHPUR', 2, 981.00),
('BBC375-NSDF-4675', 'shashi@demo.com', 10004, '2024-01-12', 'RANCHI', 'PATNA', 1, 550.00),
('BBC373-NSDF-4674', 'shashi@demo.com', 10006, '2024-07-22', 'PATNA', 'DELHI', 3, 4352.25);

SELECT * FROM ADMIN;
SELECT * FROM CUSTOMER;
SELECT * FROM TRAIN;
SELECT * FROM HISTORY;
